In [36]:
import pandas as pd

dados = pd.read_csv('data/seguro_de_vida.csv')

dados.dtypes

idade         int64
sexo         object
imc         float64
filhos        int64
fumante      object
regiao       object
despesas    float64
dtype: object

In [35]:
import pandas as pd

dados = pd.read_csv('data/seguro_de_vida.csv')

dados.isnull().sum()

idade       0
sexo        0
imc         0
filhos      0
fumante     0
regiao      0
despesas    0
dtype: int64

In [34]:
import pandas as pd

dados = pd.read_csv('data/seguro_de_vida.csv')

dados.describe()

             idade          imc       filhos      despesas
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [33]:
import pandas as pd

dados = pd.read_csv('data/seguro_de_vida.csv')

dados.describe(include='object')

             sexo fumante   regiao
count        1338    1338     1338
unique          2       2        4
top     masculino     nao  sudeste
freq          676    1064      364

In [32]:
import pandas as pd

dados = pd.read_csv('data/seguro_de_vida.csv')

int(dados['filhos'].value_counts().idxmax())

0

In [31]:
import pandas as pd

dados = pd.read_csv('data/seguro_de_vida.csv')

total_fumantes = dados['fumante'].value_counts()['sim']
total = dados['fumante'].count()
percentual_fumantes = (total_fumantes / total) * 100

format(float(percentual_fumantes), ".2f")

'20.48'

In [30]:
import pandas as pd

dados = pd.read_csv('data/seguro_de_vida.csv')

dados['regiao'].value_counts()

regiao
sudeste     364
sudoeste    325
noroeste    325
nordeste    324
Name: count, dtype: int64